services:
  frankenphp:
    build:
      context: .
    entrypoint: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=1 --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app