services:
  frankenphp:
    build:
      context: .
    entrypoint: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    environment:
      - HTTPS=true
      - APP_URL=https://api-backendrpl.achmichael.my.id
    volumes:
      - .:/app